import os
#print (os.system("date"))
#print(os.getcwd())
#os.mkdir("C:/Users/ACER/Downloads/Avikshit")
#isExist=os.path.exists("C:/Users/ACER/Downloads/Guidelines for Corrections (1).pdf")
#print(isExist)
#root_ext=os.path.splitext("C:/Users/ACER/Downloads/Guidelines for Corrections (1).pdf")
#print(root_ext)
#root_ext=os.path.splitext("C:/Users/ACER/Downloads/Avikshit")
#print(root_ext)
print(os.listdir("C:/Users/ACER/Downloads"))